<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\{User, Article};
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * The NoteFactory class is an Eloquent model factory designed to generate fake or test data for the `Note` model.
 * It facilitates the creation of note instances with realistic attributes, including associations with existing users (as authors) and articles.
 *
 * This factory extends Laravel's base `Factory` class, providing a `definition` method to specify the default structure of a note, and helper methods (`withAuthor`,
 * `withArticle`) to intelligently assign existing or new authors and articles to the generated notes. It leverages the `Faker` library for generating textual content like titles and body paragraphs.
 *
 * @see Note        - The Eloquent model this factory generates.
 * @see User        - The Eloquent model for the note's author.
 * @see Article     - The Eloquent model for the associated article.
 *
 * @extends Factory<\App\Models\Note>
 *
 * @package Database\Factories
 */
final class NoteFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * This method specifies the default attributes that a `Note` model will have when created using this factory without any specific state applied.
     * It dynamically assigns an `author_id` and `article_id` by calling the `withAuthor()` and `withArticle()` helper methods, respectively.
     * This ensures that generated notes are always linked to a valid author and article.
     * The `title` and `body` fields are populated with random sentences and paragraphs generated by the Faker instance.
     *
     * @return array<string, mixed>     An associative array representing the default attributes for a `Note` model.
     */
    public function definition(): array
    {
        return [
            'author_id' => $this->withAuthor(),
            'article_id' => $this->withArticle(),
            'title' => $this->faker->sentence(),
            'body' => $this->faker->paragraph(),
        ];
    }

    /**
     * Determines and returns the ID of an author for the note.
     *
     * This private helper method attempts to retrieve a random existing `User` from the database.
     * If an existing user is found, their `id` is returned, ensuring that the note is associated with a pre-existing author.
     * If no users are found in the database (e.g., during initial seeding before user creation), it falls back to returning a new `UserFactory` instance.
     * This factory instance will then create a new user when the note is created, ensuring a valid author relationship is always established.
     *
     * @return int|UserFactory  The ID of an existing user, or a `UserFactory` instance if no users are found.
     */
    private function withAuthor(): int|UserFactory
    {
        $randomUser = User::inRandomOrder()->first();

        if ($randomUser) {
            /** @var User $randomUser */
            return $randomUser->id;
        }

        return User::factory();
    }

    /**
     * Determines and returns the ID of an article for the note.
     *
     * This private helper method attempts to retrieve a random existing `Article` from the database.
     * If an existing article is found, its `id` is returned, ensuring that the note is associated with a pre-existing article.
     * If no articles are found in the database (e.g., during initial seeding before article creation), it falls back to returning a new `ArticleFactory` instance.
     * This factory instance will then create a new article when the note is created, ensuring a valid article relationship is always established.
     *
     * @return int|UserFactory  The ID of an existing user, or a `UserFactory` instance if no users are found.
     */
    private function withArticle(): int|UserFactory
    {
        $randomArticle = Article::inRandomOrder()->first();

        if ($randomArticle) {
            /** @var Article $randomArticle */
            return $randomArticle->id;
        }

        return Article::factory();
    }
}
