<?php

namespace Database\Factories;

use App\Models\User;
use App\UserTypes;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * The UserFactory class is an Eloquent model factory responsible for generating fake or test data for the `User` model.
 * It provides a convenient way to create multiple user instances with predefined or customized attributes for testing and seeding purposes.
 *
 * This factory extends Laravel's base `Factory` class, offering methods to define the default state of a user and to apply specific states (e.g., unverified email,
 * different user types) to generated user instances. It leverages the `Faker` library for generating realistic-looking data such as names and email addresses.
 *
 * @see User        - The Eloquent model this factory generates.
 * @see UserTypes   - The enum defining different user roles.
 *
 * @extends Factory<User>
 *
 * @package Database\Factories
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     *
     * This static property stores a hashed password that can be reused across multiple user instances generated by the factory, optimizing performance by avoiding re-hashing the same string repeatedly.
     * If `null`, a new password will be hashed the first time it's needed.
     */
    protected static ?string $password = null;

    /**
     * Define the model's default state.
     *
     * This method specifies the default attributes that a `User` model will have when created using this factory without any specific state applied. It uses
     * the `fake()` helper to generate realistic but random data for common user fields.
     *
     * The password is hashed using `Hash::make('password')` and cached in the `$password` static property for efficiency. The `email_verified_at`
     * is set to the current timestamp, indicating a verified email by default.
     *
     * @return array<string, mixed> An associative array representing the default attributes for a `User` model.
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'firstname' => fake()->firstName(),
            'lastname' => fake()->lastName(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
            'inactivity_warning_sent_at' => null,
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     *
     * This state method modifies the default attributes of a user to set their `email_verified_at` timestamp to `null`.
     * This is useful for testing scenarios where an unverified user account is required, such as testing email verification flows.
     *
     * @return static   Returns the factory instance, allowing for method chaining.
     */
    public function unverified(): static
    {
        return $this->state(fn(): array => ['email_verified_at' => null]);
    }

    /**
     * Indicate that the user should have the 'Developer' user type.
     *
     * This state method applies a specific user type to the generated user model, setting the `user_type` attribute to the value defined by `UserTypes::Developer`.
     * This is particularly useful for creating test users with specific roles for role-based access control testing.
     *
     * @return Factory<User>    Returns the factory instance, typed to the `User` model, allowing for method chaining.
     */
    public function developer(): Factory
    {
        return $this->state(fn(): array => ['user_type' => UserTypes::Developer]);
    }

    /**
     * Indicate that the user should have the 'Administrator' user type.
     *
     * This state method sets the `user_type` attribute of the generated user model to the value defined by `UserTypes::Administrators`.
     * This is essential for creating test users with administrative privileges for system administration and permission testing.
     *
     * @return Factory<User>    Returns the factory instance, typed to the `User` model, allowing for method chaining.
     */
    public function administrator(): Factory
    {
        return $this->state(fn(): array => ['user_type' => UserTypes::Administrators]);
    }

    /**
     * Indicate that the user should have the 'Editor' user type.
     *
     * This state method assigns the `user_type` attribute of the generated user model to the value defined by `UserTypes::Editor`.
     * This is useful for creating test users who have content editing permissions within the application.
     *
     * @return Factory<User>    Returns the factory instance, typed to the `User` model, allowing for method chaining.
     */
    public function editor(): Factory
    {
        return $this->state(fn(): array => ['user_type' => UserTypes::Editor]);
    }

    /**
     * Indicate that the user should have the 'EditorInChief' user type.
     *
     * This state method sets the `user_type` attribute of the generated user model to the value defined by `UserTypes::EditorInChief`.
     * This is particularly useful for creating test users with the highest level of content editing and publishing permissions.
     *
     * @return Factory<User>    Returns the factory instance, typed to the `User` model, allowing for method chaining.
     */
    public function editorInChief(): Factory
    {
        return $this->state(fn(): array => ['user_type' => UserTypes::EditorInChief]);
    }
}
