name: "Algemene melding"
description: "Meld een niet-gestandaardiseerd probleem, opmerking of suggestie."
body:
  - type: dropdown
    id: "environment"
    attributes:
      label: In welke omgeving was je het Vlaams Woordenboek aan het gebruiken toen de fout optrad?
      description: U kunt er hier een selecteren.
      multiple: false
      options:
        - --niet opegegeven--
        - Productie (www.vlaamswoordenboek.be)
        - Staging (www.staging.vlaamswoordenboek.be)
      validations:
        required: true
  - type: markdown
    attributes:
      value: |
        **Belangrijk:** Vul alle secties zo goed mogelijk in, zodat we de rapportering snelm kunnen bekijken en mogelijks behandelen.
  - type: textarea
    id: description
    attributes:
      label: Beschrijf duidelijk wat je wilt melden.
      description: Welke situatie of achtergrondinformatie is relevant?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Wat is het effect van deze melding of probleem?
  - type: textarea
    id: voorgestelde-oplossing
    attributes:
      label: Voorgestelde oplossing
      description: Welke oplossing stel je voor om het probleem te verhelpen?
  - type: textarea
    id: aanvullende-opmerkingen
    attributes:
      label: Aanvullende opmerkingen
      description: Eventuele extra details of screenshots
