<?php

declare(strict_types=1);

namespace App\Console\Commands\Maintenance;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

#[Signature('vl-wbk:livewire-cleanup')]
#[Description('Command for cleaning up the temporary files generated by Laravel Livewire')]
final class LivewireCleanupCommand extends Command
{
    public function handle()
    {
        $files = Storage::files('livewire-tmp');

        foreach ($files as $file) {
            if (now()->subHours(24)->greaterThan(Storage::lastModified($file))) {
                Storage::delete($file);
            }
        }
    }
}
